### ISSUE TITLE
Doubleclick not responding

### ISSUE THREAD

**Issue by Razeick** [League-of-Foundry-Developers/fvtt-initiative-double-click#13]
Describe the bug
Attempted to double click to change initiative from combat tracker, DnD 5e 2.0.2, Foundry Version 10.285. No response from module and no errors in console. Double clicking only opens actor sheet

To Reproduce

    Open combat tracker
    Have active combatants
    Start Combat with already rolled initiative
    Double click initiative value in combat tracker

Expected behavior
A dialogue box appears allowing for user to enter new initiative value

Additional context
No error in the console. Only Initiative Double Click and libwrapper were enabled, fresh v10 campaign.

**Comment by mclemente** [comment]
This was fixed with #15.
