### ISSUE TITLE
Disable dice roll prompt

### ISSUE THREAD

**Issue by RandomLegend** [League-of-Foundry-Developers/fvtt-initiative-double-click#14]
Hello,

is it possible to disable the dice prompt when adding a token that doesn't already have a set initiative?

https://user-images.githubusercontent.com/38812603/219710204-c33840b6-6916-439a-ba0e-98fbaf1c17d6.mp4

Here you can see that when a Token already got an initiative it doesn't open anything if clicked. If the dice is still there it opens the prompt.

**Comment by mclemente** [comment]
This is a system-specific feature of dnd5e. You're better off requesting it there.
