### ISSUE TITLE
langs directory is missing in release

### ISSUE THREAD

**Issue by shemetz** [League-of-Foundry-Developers/fvtt-initiative-double-click#4]
```
FoundryVTT | 2021-08-21 15:04:50 | [error] Invalid language definition in Package initiative-double-click: Language JSON path langs/en.json does not exist
```

I believe this is because the new `langs` directory is not included in the `main.yml` file of the github workflow.

I created a pull request [here](https://github.com/League-of-Foundry-Developers/fvtt-initiative-double-click/pull/3) (#3)

**Comment by mclemente** [comment]
Sorry, I didn't have the notifications on for this repo. Thanks for fixing it!
