### ISSUE TITLE
Request. Revert to Rolled Initiative etc.

### ISSUE THREAD

**Issue by simulacrum-1** [League-of-Foundry-Developers/fvtt-initiative-double-click#5]
This is a great module. Thanks!
I have a request. In WFRP there are some situations that mean you may go last in the initiative or even first. So this module is brilliant.
However, I have to write down what the persons Initiative roll was before so I can revert.
Here are 3 ideas I'd love to see in the module.
1. Revert: It would take you back to the initial rolled value so I can go back to the correct order once the effect has ended. I'm sure other systems may benefit from this too.
2. First and Last options: As some situations call for this and it would make it simple to just click a button rather than type in a number.
2. Draw Order: Be able to specify a statistic that it uses to calculate order in case of a draw.

**Comment by mclemente** [comment]
Hey, I managed to get 1 and 2, check the settings on 1.4.

Draw Order is a bit too much since it varies from system to system and I'm not planning on doing that.

**Comment by simulacrum-1** [comment]
Hey thanks. That's great! I'll try it out
