### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'children')

### ISSUE THREAD

**Issue by Doresain** [League-of-Foundry-Developers/fvtt-initiative-double-click#8]
On latest version and foundry v9 stable. The module seems to function as expected, but I get this error on page load whether there is an active combat or not.

![image](https://user-images.githubusercontent.com/26096062/149640780-1e988b1b-0ff9-465e-ba4e-86608549942c.png)

**Comment by mclemente** [comment]
Yes, I haven't set up a check if the combat existed before trying to read it.
