### ISSUE TITLE
Double left clicking also opens referenced object sheet

### ISSUE THREAD

**Issue by PepijnMC** [League-of-Foundry-Developers/fvtt-initiative-double-click#9]
As the title states, double left clicking an initiative entry already has an action, it opens the token's character sheet. This is rather annoying, especially because this particular key binding can't be changed within Foundry. Could this be disabled or could perhaps a setting be added to edit initiative values with just a single left click to circumvent this issue?

**Comment by ckdragons** [comment]
Confirmed. This happens to me as well. Running Foundry v9.

**Comment by geoidesic** [comment]
Should be simple enough to prevent bubbling up of the dbl-click event?
